[package]
name = "safe_pump"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
spl-discriminator = "0.4.1"
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.30.1", features = ["memo"] }
solana-program = "2.2.1"
spl-token = { git = "https://github.com/hamkj7hpo/solana-program-library.git", rev = "746fbdbba38760fd57e7bd6687d27ad4c0cd50f4" }
spl-associated-token-account = { git = "https://github.com/hamkj7hpo/solana-program-library.git", rev = "746fbdbba38760fd57e7bd6687d27ad4c0cd50f4" }
spl-token-2022 = { git = "https://github.com/hamkj7hpo/token-2022.git", rev = "f15553da342ac7fad79dca15ea3a1c74af202d79" }
spl-pod = "0.4.0"
spl-token-group-interface = "0.2.4"
spl-token-metadata-interface = "0.3.4"
spl-transfer-hook-interface = "0.6.4"
spl-type-length-value = "0.6.0"
solana-zk-sdk = "2.1.0"
raydium-cp-swap = { git = "https://github.com/hamkj7hpo/raydium-cp-swap.git", rev = "7bb5704601284d4380f803e24502c8f2e5c2eb13", features = ["cpi"] }
bytemuck = { version = "1.18.0", features = ["derive"] }
bincode = "1.3.3"
zeroize = "1.3.0"

[features]
cpi = []

[profile.release]
overflow-checks = true
