[package]
name = "safe_pump"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
# Core Rust utilities
base64ct = "1.6.0"
bincode = "1.3.3"
bytemuck = { git = "https://github.com/Lokathor/bytemuck.git", branch = "main", features = ["derive"] }
bytemuck_derive = { git = "https://github.com/Lokathor/bytemuck.git", branch = "main" }
zeroize = { git = "ssh://git@github.com/hamkj7hpo/utils.git", branch = "safe-pump-compat", version = "1.3.0", optional = true }
rand = { git = "https://github.com/rust-random/rand.git", branch = "master" }
sha3 = { git = "https://github.com/RustCrypto/hashes.git", branch = "master" }
merlin = { git = "https://github.com/dalek-cryptography/merlin.git", branch = "master" }
curve25519-dalek = { git = "ssh://git@github.com/hamkj7hpo/curve25519-dalek.git", branch = "safe-pump-compat-v2", features = ["std", "serde"] }
light-poseidon = "0.3.0"
getrandom = { version = "0.2.15", features = ["custom"] }
itertools = { git = "https://github.com/rust-itertools/itertools.git", branch = "master" }
lazy_static = { git = "https://github.com/rust-lang-nursery/lazy-static.rs.git", branch = "master" }
num = { git = "https://github.com/rust-num/num.git", branch = "master" }
num-derive = { git = "https://github.com/rust-num/num-derive.git", branch = "master" }
num-traits = { git = "https://github.com/rust-num/num-traits.git", branch = "master" }
serde = { git = "https://github.com/serde-rs/serde.git", branch = "master" }
serde_derive = { git = "https://github.com/serde-rs/serde.git", branch = "master" }
serde_json = { git = "https://github.com/serde-rs/json.git", branch = "master" }
subtle = { git = "https://github.com/dalek-cryptography/subtle.git", branch = "main" }
thiserror = { git = "https://github.com/dtolnay/thiserror.git", branch = "master" }
tiny-bip39 = { git = "https://github.com/maciejhirsz/tiny-bip39.git", branch = "master" }
uint = { git = "https://github.com/paritytech/parity-common.git", branch = "master" }
wasm-bindgen = "=0.2.93"
js-sys = "=0.3.70"
aes-gcm-siv = { git = "https://github.com/RustCrypto/AEADs.git", branch = "master" }

# Solana fork & SPL dependencies
solana-program = { git = "ssh://git@github.com/hamkj7hpo/solana.git", branch = "safe-pump-compat" }
spl-pod = { git = "ssh://git@github.com/hamkj7hpo/spl-pod.git", branch = "safe-pump-compat" }
spl-associated-token-account = { git = "ssh://git@github.com/hamkj7hpo/associated-token-account.git", branch = "safe-pump-compat", package = "spl-associated-token-account" }
spl-tlv-account-resolution = { git = "ssh://git@github.com/hamkj7hpo/spl-type-length-value.git", branch = "safe-pump-compat", package = "spl-tlv-account-resolution" }
spl-discriminator = { git = "ssh://git@github.com/hamkj7hpo/solana-program-library.git", branch = "safe-pump-compat", package = "spl-discriminator" }
spl-token-2022 = { git = "ssh://git@github.com/hamkj7hpo/token-2022.git", branch = "safe-pump-compat", package = "spl-token-2022", default-features = false }
spl-memo = { git = "ssh://git@github.com/hamkj7hpo/memo.git", branch = "safe-pump-compat", package = "spl-memo", version = "6.0.0" }
spl-transfer-hook-interface = { git = "ssh://git@github.com/hamkj7hpo/transfer-hook.git", branch = "safe-pump-compat", package = "spl-transfer-hook-interface" }
spl-token-metadata-interface = { git = "ssh://git@github.com/hamkj7hpo/token-metadata.git", branch = "safe-pump-compat", package = "spl-token-metadata-interface" }
spl-token-group-interface = { git = "ssh://git@github.com/hamkj7hpo/token-group.git", branch = "safe-pump-compat", package = "spl-token-group-interface" }

# Anchor
anchor-lang = { git = "ssh://git@github.com/hamkj7hpo/anchor.git", branch = "safe-pump-compat", package = "anchor-lang", features = ["init-if-needed"] }
anchor-spl = { git = "ssh://git@github.com/hamkj7hpo/anchor.git", branch = "safe-pump-compat", package = "anchor-spl", default-features = false }

# Raydium
raydium-cp-swap = { git = "ssh://git@github.com/hamkj7hpo/raydium-cp-swap.git", branch = "safe-pump-compat", package = "raydium-cp-swap", default-features = false }

# zk-SDK
solana-zk-sdk = { git = "ssh://git@github.com/hamkj7hpo/zk-elgamal-proof.git", branch = "safe-pump-compat", package = "solana-zk-sdk" }

[features]
cpi = []

[profile.release]
overflow-checks = true
