[package]
name = "safe_pump"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
spl-discriminator = "0.4.1"
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.29.0", features = ["memo"] }
solana-program = "2.1.0"
spl-token = "5.0.0"
spl-associated-token-account = "3.0.2"
spl-token-2022 = { git = "https://github.com/hamkj7hpo/token-2022.git", rev = "2099caa13da83a3c3f968abba43f15cadd677aff" }
spl-pod = "0.4.0"
spl-token-group-interface = "0.2.4"
spl-token-metadata-interface = "0.3.4"
spl-transfer-hook-interface = "0.6.4"
spl-type-length-value = "0.6.0"
solana-zk-sdk = "2.1.0"
raydium-cp-swap = { git = "https://github.com/hamkj7hpo/raydium-cp-swap.git", rev = "8887ceeb55e76d8fb1a39eb444a8b0c93ca5f6cd", features = ["cpi"] }
bytemuck = { version = "1.18.0", features = ["derive"] }
bincode = "1.3.3"
zeroize = "1.3.0"

[features]
cpi = []

[profile.release]
overflow-checks = true
