[package]
name = "safe_pump"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
base64ct = { version = "=1.6.0" }
bincode = "1.3.3"
bytemuck = { version = "1.18.0", features = ["derive"] }
zeroize = "1.3.0"
spl-tlv-account-resolution = { git = "https://github.com/hamkj7hpo/spl-type-length-value.git", rev = "50f00a65bf318481de4295cacb0253cc5db2ca58", package = "spl-tlv-account-resolution" }
spl-discriminator = { git = "https://github.com/hamkj7hpo/solana-program-library.git", rev = "db0bae1a3397b64e22058cca88145952c5e0b7de", package = "spl-discriminator" }
spl-associated-token-account = { git = "https://github.com/hamkj7hpo/associated-token-account.git", rev = "cb4047956ff0830ca864b31dfdec07bb98bea452", default-features = false }
spl-token-2022 = { git = "https://github.com/hamkj7hpo/token-2022.git", rev = "c07e6ca26968aef868a8f8db90aa0286927cb367", package = "spl-token-2022", default-features = false }
solana-zk-sdk = { git = "https://github.com/hamkj7hpo/zk-elgamal-proof.git", rev = "b0a83885270a06e0fa110882ce094e4e535ac1e1", package = "solana-zk-sdk" }
spl-pod = { git = "https://github.com/hamkj7hpo/spl-pod.git", rev = "2bcbbd69db3cb6094beaeb28e4e0c6ae01ae6f64", default-features = false }
anchor-spl = { git = "https://github.com/hamkj7hpo/anchor.git", rev = "733602ae380bba4fa9f5d820aa3710c62e534a4e", default-features = false }
raydium-cp-swap = { git = "https://github.com/hamkj7hpo/raydium-cp-swap.git", rev = "8fff0dd4c019eaee2e7580b15a48fca378b2c7ed", package = "raydium-cp-swap", default-features = false }
spl-type-length-value = { git = "https://github.com/hamkj7hpo/spl-type-length-value.git", rev = "50f00a65bf318481de4295cacb0253cc5db2ca58", package = "spl-type-length-value" }
spl-transfer-hook-interface = { git = "https://github.com/hamkj7hpo/transfer-hook.git", rev = "faeabf52625ac12e2a6cc5e7618854d8fa676d18", package = "spl-transfer-hook-interface" }
spl-token-metadata-interface = { git = "https://github.com/hamkj7hpo/token-metadata.git", rev = "f5a9a37ddbfb05df76021ada4648273be9466c8d", package = "spl-token-metadata-interface" }
spl-token-group-interface = { git = "https://github.com/hamkj7hpo/token-group.git", rev = "5442931aec8184db4c1b387be3c663fa42fccb41", package = "spl-token-group-interface" }
spl-memo = { git = "https://github.com/hamkj7hpo/memo.git", rev = "7d7a67db8f24bc56bb6b415a8da112ebc5f19a53", package = "spl-memo", version = "6.0.0" }
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", rev = "079536b934de349771fa8a0e9945bcef01f529cc", package = "solana-program" }
anchor-lang = { git = "https://github.com/hamkj7hpo/anchor.git", rev = "733602ae380bba4fa9f5d820aa3710c62e534a4e", features = ["init-if-needed"] }
bytemuck = { version = "1.18.0", features = ["derive"] }
bincode = "1.3.3"
base64ct = { version = "=1.6.0" }

[features]
cpi = []

[profile.release]
overflow-checks = true


[patch.crates-io]
curve25519-dalek = { git = "https://github.com/hamkj7hpo/curve25519-dalek.git", branch = "safe-pump-compat-v2" }
spki = { git = "https://github.com/hamkj7hpo/formats.git", branch = "safe-pump-compat", package = "spki" }
spl-type-length-value = { git = "https://github.com/hamkj7hpo/spl-type-length-value.git", rev = "50f00a65bf318481de4295cacb0253cc5db2ca58", package = "spl-type-length-value" }
spl-memo = { git = "https://github.com/hamkj7hpo/memo.git", rev = "7d7a67db8f24bc56bb6b415a8da112ebc5f19a53", package = "spl-memo", version = "6.0.0" }
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", rev = "079536b934de349771fa8a0e9945bcef01f529cc", package = "solana-program" }
spl-tlv-account-resolution = { git = "https://github.com/hamkj7hpo/spl-type-length-value.git", rev = "50f00a65bf318481de4295cacb0253cc5db2ca58", package = "spl-tlv-account-resolution" }
spl-discriminator = { git = "https://github.com/hamkj7hpo/solana-program-library.git", rev = "db0bae1a3397b64e22058cca88145952c5e0b7de", package = "spl-discriminator" }
spl-associated-token-account = { git = "https://github.com/hamkj7hpo/associated-token-account.git", rev = "cb4047956ff0830ca864b31dfdec07bb98bea452", default-features = false }
spl-token-2022 = { git = "https://github.com/hamkj7hpo/token-2022.git", rev = "c07e6ca26968aef868a8f8db90aa0286927cb367", package = "spl-token-2022", default-features = false }
solana-zk-sdk = { git = "https://github.com/hamkj7hpo/zk-elgamal-proof.git", rev = "b0a83885270a06e0fa110882ce094e4e535ac1e1", package = "solana-zk-sdk" }
spl-pod = { git = "https://github.com/hamkj7hpo/spl-pod.git", rev = "2bcbbd69db3cb6094beaeb28e4e0c6ae01ae6f64", default-features = false }
anchor-spl = { git = "https://github.com/hamkj7hpo/anchor.git", rev = "733602ae380bba4fa9f5d820aa3710c62e534a4e", default-features = false }
