[package]
name = "safe_pump"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
spl-discriminator = "0.4.1"
anchor-lang = { git = "https://github.com/hamkj7hpo/anchor.git", rev = "dbfdadca848af65a4bd8b48b777a30ca9af1430d", features = ["init-if-needed"] }
anchor-spl = { version = "0.29.0", features = ["memo"] }
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", rev = "5208a7870826307290c30b7d80768f40267433a1" }
spl-token = "4.0.0"
spl-associated-token-account = { git = "https://github.com/hamkj7hpo/associated-token-account.git", rev = "a504320c1f48537eb8391c3e5621d9c971660fca" }
spl-token-2022 = { git = "https://github.com/hamkj7hpo/token-2022.git", rev = "2099caa13da83a3c3f968abba43f15cadd677aff" }
spl-pod = "0.4.0"
spl-token-group-interface = "0.2.4"
spl-token-metadata-interface = "0.3.4"
spl-transfer-hook-interface = "0.6.4"
spl-type-length-value = "0.6.0"
solana-zk-sdk = "2.1.0"
raydium-cp-swap = { git = "https://github.com/hamkj7hpo/raydium-cp-swap.git", rev = "69fd7d3140c31d34b37a850bba4cfb31b43839a4", features = ["cpi"] }
bytemuck = { version = "1.18.0", features = ["derive"] }
bincode = "1.3.3"
zeroize = "1.0.0"

[features]
cpi = []

[profile.release]
overflow-checks = true
