[package]
name = "safe_pump"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
# Core Rust utilities
base64ct = { git = "git@github.com:hamkj7hpo/base64ct.git", branch = "safe-pump-compat" }
bincode = { git = "git@github.com:hamkj7hpo/bincode.git", branch = "safe-pump-compat" }
bytemuck = { git = "git@github.com:hamkj7hpo/bytemuck.git", branch = "safe-pump-compat", features = ["derive"] }
zeroize = { git = "git@github.com:hamkj7hpo/zeroize.git", branch = "safe-pump-compat" }
rand = { git = "git@github.com:hamkj7hpo/rand.git", branch = "safe-pump-compat" }
sha3 = { git = "git@github.com:hamkj7hpo/sha3.git", branch = "safe-pump-compat" }
merlin = { git = "git@github.com:hamkj7hpo/merlin.git", branch = "safe-pump-compat" }
curve25519-dalek = { git = "https://github.com/hamkj7hpo/curve25519-dalek.git", branch = "safe-pump-compat-v2", features = ["serde"] }

# Solana fork & SPL dependencies
solana-program = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
spl-pod = { git = "git@github.com:hamkj7hpo/spl-pod.git", rev = "2bcbbd69", default-features = false }
spl-associated-token-account = { git = "git@github.com:hamkj7hpo/associated-token-account.git", rev = "cb404795" }
spl-tlv-account-resolution = { git = "git@github.com:hamkj7hpo/spl-type-length-value.git", rev = "50f00a65" }
spl-discriminator = { git = "git@github.com:hamkj7hpo/solana-program-library.git", rev = "425379d49" }
spl-token-2022 = { git = "git@github.com:hamkj7hpo/token-2022.git", rev = "c07e6ca2", package = "spl-token-2022", default-features = false }
spl-memo = { git = "git@github.com:hamkj7hpo/memo.git", rev = "7d7a67db", package = "spl-memo", version = "6.0.0" }
spl-transfer-hook-interface = { git = "git@github.com:hamkj7hpo/transfer-hook.git", rev = "faeabf52", package = "spl-transfer-hook-interface" }
spl-token-metadata-interface = { git = "git@github.com:hamkj7hpo/token-metadata.git", rev = "f5a9a37d", package = "spl-token-metadata-interface" }
spl-token-group-interface = { git = "git@github.com:hamkj7hpo/token-group.git", rev = "5442931a", package = "spl-token-group-interface" }

# Anchor
anchor-lang = { git = "git@github.com:hamkj7hpo/anchor.git", rev = "733602ae", features = ["init-if-needed"] }
anchor-spl = { git = "git@github.com:hamkj7hpo/anchor.git", rev = "733602ae", default-features = false }

# Raydium
raydium-cp-swap = { git = "git@github.com:hamkj7hpo/raydium-cp-swap.git", rev = "33d438c6", package = "raydium-cp-swap", default-features = false }

# zk-SDK
solana-zk-sdk = { git = "git@github.com:hamkj7hpo/zk-elgamal-proof.git", branch = "safe-pump-compat" }

[features]
cpi = []

[profile.release]
overflow-checks = true

[patch.crates-io]
curve25519-dalek = { git = "git@github.com:hamkj7hpo/curve25519-dalek.git", branch = "safe-pump-compat-v2" }
solana-program = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
spl-pod = { git = "git@github.com:hamkj7hpo/spl-pod.git", rev = "2bcbbd69", default-features = false }
spl-type-length-value = { git = "git@github.com:hamkj7hpo/spl-type-length-value.git", rev = "50f00a65" }
spl-memo = { git = "git@github.com:hamkj7hpo/memo.git", rev = "7d7a67db", version = "6.0.0" }
spl-associated-token-account = { git = "git@github.com:hamkj7hpo/associated-token-account.git", rev = "cb404795" }
solana-zk-sdk = { git = "git@github.com:hamkj7hpo/zk-elgamal-proof.git", branch = "safe-pump-compat" }
solana-instruction = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
solana-pubkey = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
solana-sdk-ids = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
solana-derivation-path = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
solana-seed-derivable = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
solana-seed-phrase = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
solana-signature = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
solana-signer = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
solana-keypair = { git = "git@github.com:hamkj7hpo/solana.git", rev = "079536b9" }
